(() => {
  const body = document.getElementById('inventory-body');
  const escapeHtml = value => String(value).replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const productFilter=document.getElementById('inventory-filter-product'),locationFilter=document.getElementById('inventory-filter-location'),statusFilter=document.getElementById('inventory-filter-status'),summary=document.getElementById('inventory-filter-summary');
  const movementBody=document.getElementById('movement-body'),movementProduct=document.getElementById('movement-filter-product'),movementLocation=document.getElementById('movement-filter-location'),movementType=document.getElementById('movement-filter-type'),movementFrom=document.getElementById('movement-filter-from'),movementTo=document.getElementById('movement-filter-to'),movementSummary=document.getElementById('movement-filter-summary');
  let allRows=[];
  let allMovements=[];
  const movementLabels={receipt:'Entrada',sale:'Venta',count_adjustment:'Ajuste de conteo',return_fit:'Devolución apta',loss:'Merma'};
  const money=value=>value==null?'—':new Intl.NumberFormat('es-EC',{style:'currency',currency:'USD'}).format(Number(value));
  function render(){const query=productFilter.value.trim().toLowerCase(),location=locationFilter.value,status=statusFilter.value;const rows=allRows.filter(row=>{const text=`${row.product_name} ${row.sku}`.toLowerCase();const state=!status||(status==='available'&&row.available>0)||(status==='low'&&row.available>0&&row.available<=5)||(status==='empty'&&row.available===0)||(status==='expiring'&&row.expiring_lots>0);return(!query||text.includes(query))&&(!location||row.location_id===location)&&state});summary.textContent=`Mostrando ${rows.length} de ${allRows.length} registros`;body.innerHTML=rows.length?rows.map(row=>`<tr><td><strong>${escapeHtml(row.product_name)}</strong></td><td>${escapeHtml(row.sku)}</td><td>${escapeHtml(row.location_id)}</td><td>${row.available}</td><td>${row.reserved}</td><td><span class="status-pill ${row.expiring_lots?'warn':''}">${row.expiring_lots?`${row.expiring_lots} lote(s)`:'Sin alerta'}</span></td></tr>`).join(''):'<tr><td colspan="6">No hay existencias que coincidan con los filtros.</td></tr>'}
  async function loadInventory() {
    const response = await fetch('/api/v1/inventory'); const payload = await response.json();
    const rows = payload.data || [];allRows=rows;
    document.getElementById('inventory-products').textContent = rows.length;
    document.getElementById('inventory-units').textContent = rows.reduce((sum,row)=>sum+row.available,0);
    document.getElementById('inventory-low').textContent = rows.filter(row=>row.available<=5).length;
    document.getElementById('inventory-expiring').textContent = rows.reduce((sum,row)=>sum+row.expiring_lots,0);
    const current=locationFilter.value;locationFilter.innerHTML='<option value="">Todas las ubicaciones</option>'+[...new Set(rows.map(x=>x.location_id))].sort().map(x=>`<option value="${escapeHtml(x)}">${escapeHtml(x)}</option>`).join('');locationFilter.value=current;render();
  }
  function renderMovements(){const query=movementProduct.value.trim().toLowerCase(),location=movementLocation.value,type=movementType.value,from=movementFrom.value?new Date(`${movementFrom.value}T00:00:00`):null,to=movementTo.value?new Date(`${movementTo.value}T23:59:59.999`):null;const rows=allMovements.filter(row=>{const occurred=new Date(row.occurred_at),text=`${row.product_name} ${row.sku}`.toLowerCase();return(!query||text.includes(query))&&(!location||row.location_id===location)&&(!type||row.type===type)&&(!from||occurred>=from)&&(!to||occurred<=to)});movementSummary.textContent=`Mostrando ${rows.length} de ${allMovements.length} movimientos`;movementBody.innerHTML=rows.length?rows.map(row=>`<tr><td>${new Date(row.occurred_at).toLocaleString('es-EC')}</td><td><strong>${escapeHtml(row.product_name)}</strong></td><td>${escapeHtml(row.sku||'—')}</td><td><span class="status-pill ${row.type==='loss'?'warn':''}">${escapeHtml(movementLabels[row.type]||row.type)}</span></td><td><strong>${Number(row.quantity)>0?'+':''}${row.quantity}</strong></td><td>${escapeHtml(row.location_id||'—')}</td><td>${money(row.unit_cost)}</td><td>${escapeHtml(row.source_type||'—')}</td><td>${escapeHtml(row.actor_name||'Sistema')}</td></tr>`).join(''):'<tr><td colspan="9">No hay movimientos que coincidan con los filtros.</td></tr>'}
  async function loadMovements(){const response=await fetch('/api/v1/inventory/movements?limit=500'),payload=await response.json();if(!response.ok){movementBody.innerHTML=`<tr><td colspan="9">${escapeHtml(payload.error?.message||'No se pudieron cargar los movimientos.')}</td></tr>`;return}allMovements=payload.data||[];const current=movementLocation.value;movementLocation.innerHTML='<option value="">Todas las ubicaciones</option>'+[...new Set(allMovements.map(x=>x.location_id).filter(Boolean))].sort().map(x=>`<option value="${escapeHtml(x)}">${escapeHtml(x)}</option>`).join('');movementLocation.value=current;renderMovements()}
  document.getElementById('inventory-refresh').addEventListener('click', loadInventory);
  [productFilter,locationFilter,statusFilter].forEach(control=>control.addEventListener('input',render));
  document.getElementById('inventory-clear-filters').addEventListener('click',()=>{productFilter.value='';locationFilter.value='';statusFilter.value='';render()});
  document.getElementById('movement-refresh').addEventListener('click',loadMovements);
  [movementProduct,movementLocation,movementType,movementFrom,movementTo].forEach(control=>control.addEventListener('input',renderMovements));
  document.getElementById('movement-clear-filters').addEventListener('click',()=>{movementProduct.value='';movementLocation.value='';movementType.value='';movementFrom.value='';movementTo.value='';renderMovements()});
  window.addEventListener('ci:pagechange', event => { if (event.detail?.page === 'inventario'){loadInventory();loadMovements()} });
  loadInventory();loadMovements();
})();
