(()=>{
  const form=document.getElementById('report-form'),message=document.getElementById('report-message'),preview=document.getElementById('report-preview-content'),title=document.getElementById('report-preview-title'),pdfButton=document.getElementById('report-pdf'),escape=window.ciEscape||String;
  if(!form)return;
  const presets=document.createElement('div');presets.className='report-presets';presets.innerHTML='<span>Plantillas rápidas</span><div><button type="button" class="btn active" data-report-preset="general">Resumen general</button><button type="button" class="btn" data-report-preset="cash">Ventas y pagos</button><button type="button" class="btn" data-report-preset="stock">Inventario y margen</button><button type="button" class="btn" data-report-preset="customers">Clientes</button></div>';
  form.querySelector('.report-checks').before(presets);
  const tools=document.createElement('div');tools.className='report-selection-tools';tools.innerHTML='<button type="button" data-report-all>Seleccionar todo</button><button type="button" data-report-none>Limpiar selección</button><label>Periodo rápido<select data-report-period><option value="">Personalizado</option><option value="7">Últimos 7 días</option><option value="30">Últimos 30 días</option><option value="month">Este mes</option></select></label>';
  form.querySelector('.report-checks').after(tools);
  const sections=()=>[...form.querySelectorAll('[name="sections"]')].filter(input=>(window.ciAllowedReportSections?.()||[]).includes(input.value));
  const presetMap={general:['sales','inventory','margins','customers','losses','payments','forecasts'],cash:['sales','payments','losses'],stock:['inventory','margins','forecasts'],customers:['customers','sales']};
  function selectSections(values){sections().forEach(input=>input.checked=values.includes(input.value))}
  presets.querySelectorAll('[data-report-preset]').forEach(button=>button.onclick=()=>{presets.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===button));selectSections(presetMap[button.dataset.reportPreset])});
  tools.querySelector('[data-report-all]').onclick=()=>selectSections(sections().map(x=>x.value));tools.querySelector('[data-report-none]').onclick=()=>selectSections([]);
  tools.querySelector('[data-report-period]').onchange=e=>{const today=new Date(),from=new Date(today);if(e.target.value==='month')from.setDate(1);else if(e.target.value)from.setDate(today.getDate()-Number(e.target.value)+1);else return;form.date_from.value=from.toISOString().slice(0,10);form.date_to.value=today.toISOString().slice(0,10)};
  function payload(){const data=new FormData(form),selected=data.getAll('sections');if(!selected.length)throw new Error('Selecciona al menos una sección.');return{title:data.get('title'),sections:selected,date_from:data.get('date_from')||null,date_to:data.get('date_to')||null}}
  function render(snapshot){title.textContent=snapshot.title;preview.className='report-preview-content';preview.innerHTML=`<div class="report-preview-meta"><span>Generado ${new Date(snapshot.generated_at).toLocaleString('es-EC')}</span><span>${snapshot.sections.length} secciones</span></div>`+snapshot.sections.map(section=>`<section class="report-section"><div class="report-section-head"><h3>${escape(section.label)}</h3><div>${Object.entries(section.metrics||{}).map(([key,value])=>`<span><small>${escape(key.replaceAll('_',' '))}</small><strong>${escape(value)}</strong></span>`).join('')}</div></div><div class="table-wrap"><table class="data-table"><thead><tr>${section.columns.map(column=>`<th>${escape(column)}</th>`).join('')}</tr></thead><tbody>${section.rows.length?section.rows.slice(0,100).map(row=>`<tr>${row.map(value=>`<td>${escape(value)}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${section.columns.length}">Sin datos para el periodo seleccionado.</td></tr>`}</tbody></table></div>${section.rows.length>100?`<p class="filter-summary">Vista limitada a 100 de ${section.rows.length} registros. El PDF contiene el conjunto preparado por el servidor.</p>`:''}</section>`).join('')}
  async function previewReport(){try{const r=await fetch('/api/v1/reports/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())}),o=await r.json();if(!r.ok)throw new Error(o.error?.message||'No se pudo generar la vista previa');render(o.data);message.className='form-message success';message.textContent='Vista previa actualizada.'}catch(error){message.className='form-message error';message.textContent=error.message}}
  form.onsubmit=e=>{e.preventDefault();previewReport()};
  pdfButton.onclick=async()=>{try{pdfButton.disabled=true;message.className='form-message info';message.textContent='Preparando el PDF…';const r=await fetch('/api/v1/reports/pdf',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});if(!r.ok){const o=await r.json();throw new Error(o.error?.message||'No se pudo generar el PDF')}const blob=await r.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${form.title.value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-')||'informe'}.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1500);message.className='form-message success';message.textContent='PDF descargado correctamente.'}catch(error){message.className='form-message error';message.textContent=error.message}finally{pdfButton.disabled=false}};
  selectSections(presetMap.general);
})();
