(()=>{
  const escape=window.ciEscape||String;
  document.querySelectorAll('[data-management-tab]').forEach(button=>button.addEventListener('click',()=>{
    document.querySelectorAll('[data-management-tab]').forEach(x=>x.classList.toggle('active',x===button));
    document.querySelectorAll('[data-management-panel]').forEach(x=>x.classList.toggle('active',x.dataset.managementPanel===button.dataset.managementTab));
  }));
  async function loadCatalog(kind){const target=document.querySelector(`[data-list="${kind}"]`);if(!target)return;const r=await fetch(`/api/v1/${kind}`),o=await r.json(),rows=o.data||[];target.innerHTML=rows.length?rows.map(x=>`<div class="management-row"><span><strong>${escape(x.name)}</strong><small>${escape(x.code)}</small></span><span class="status-pill">${x.active===false?'Inactivo':'Activo'}</span></div>`).join(''):'<div class="empty-state compact"><p>Sin registros.</p></div>'}
  document.querySelectorAll('.management-form[data-kind]').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const kind=form.dataset.kind,data=Object.fromEntries(new FormData(form).entries()),message=form.nextElementSibling,r=await fetch(`/api/v1/${kind}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),o=await r.json();message.className=`form-message ${r.ok?'success':'error'}`;message.textContent=r.ok?'Registro creado correctamente.':(o.error?.message||'No se pudo guardar');if(r.ok){form.reset();await loadCatalog(kind)}}));
  async function loadUsers(){const [ur,rr]=await Promise.all([fetch('/api/v1/security/users'),fetch('/api/v1/security/roles')]),users=await ur.json(),roles=await rr.json(),select=document.getElementById('management-role');select.innerHTML=(roles.data||[]).map(x=>`<option value="${escape(x.code)}">${escape(x.name)}</option>`).join('');document.getElementById('management-users-body').innerHTML=(users.data||[]).map(x=>`<tr><td>${escape(x.name)}</td><td>${escape(x.email)}</td><td>${escape((x.roles||[]).join(', '))}</td><td><span class="status-pill">${escape(x.status)}</span></td></tr>`).join('')||'<tr><td colspan="4">Sin usuarios.</td></tr>'}
  document.getElementById('management-user-form')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,data=Object.fromEntries(new FormData(form).entries());data.roles=[data.roles];const r=await fetch('/api/v1/security/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),o=await r.json(),message=document.getElementById('management-user-message');message.className=`form-message ${r.ok?'success':'error'}`;message.textContent=r.ok?'Usuario creado correctamente.':(o.error?.message||'No se pudo crear');if(r.ok){form.reset();await loadUsers()}});
  async function loadSettings(){const r=await fetch('/api/v1/security/settings'),o=await r.json(),form=document.getElementById('business-settings-form');if(!r.ok||!form)return;Object.entries(o.data).forEach(([key,value])=>{if(form.elements[key])form.elements[key].value=value})}
  document.getElementById('business-settings-form')?.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget).entries());data.low_stock_threshold=Number(data.low_stock_threshold);data.expiry_warning_days=Number(data.expiry_warning_days);const r=await fetch('/api/v1/security/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),o=await r.json(),message=document.getElementById('business-settings-message');message.className=`form-message ${r.ok?'success':'error'}`;message.textContent=r.ok?'Configuración guardada.':(o.error?.message||'No se pudo guardar')});
  document.getElementById('management-users-refresh')?.addEventListener('click',loadUsers);
  Promise.all(['categories','suppliers','locations'].map(loadCatalog));loadUsers();loadSettings();
})();
