(()=>{
  const escape=window.ciEscape||String;
  const tabs=document.querySelector('.management-tabs'),configurationTab=document.querySelector('[data-management-tab="configuracion"]');
  const rolesTab=document.createElement('button');rolesTab.className='btn';rolesTab.dataset.managementTab='roles';rolesTab.textContent='Roles y permisos';tabs?.insertBefore(rolesTab,configurationTab);
  const rolesPanel=document.createElement('div');rolesPanel.className='management-panel';rolesPanel.dataset.managementPanel='roles';rolesPanel.innerHTML='<div class="management-grid"><section class="panel"><div class="panel-head"><div><span class="eyebrow">Control de acceso</span><h2>Nuevo rol</h2></div></div><form id="management-role-form" class="management-form stacked"><label>Código<input name="code" required pattern="[a-z][a-z0-9_-]{2,39}" placeholder="encargado_bodega"></label><label>Nombre<input name="name" required minlength="3" placeholder="Encargado de bodega"></label><fieldset class="permission-grid" id="management-permissions"><legend>Permisos</legend></fieldset><button class="btn btn-primary">Crear rol</button></form><p id="management-role-message" class="form-message"></p></section><section class="panel"><div class="panel-head"><div><span class="eyebrow">RBAC</span><h2>Roles disponibles</h2></div><button class="btn" id="management-roles-refresh">Actualizar</button></div><div id="management-roles-list" class="management-list"></div></section></div>';
  document.querySelector('[data-management-panel="configuracion"]')?.before(rolesPanel);
  const catalogGrid=document.querySelector('[data-management-panel="catalogos"] .management-grid'),productPanel=document.createElement('section');productPanel.className='panel product-management';productPanel.innerHTML='<div class="panel-head"><div><span class="eyebrow">Catálogo comercial</span><h2>Productos</h2></div><button class="btn" id="management-products-refresh">Actualizar</button></div><form id="management-product-form" class="product-management-form"><label>SKU<input name="sku" required maxlength="40" placeholder="CAF-001"></label><label>Nombre<input name="name" required minlength="2" placeholder="Café molido 500 g"></label><label>Código de barras<input name="barcode" maxlength="60" placeholder="7501234567890"></label><label>Unidad<input name="unit" required value="unidad"></label><label>Categoría<select name="category_id" id="management-product-category"><option value="">Sin categoría</option></select></label><label>Proveedor<select name="supplier_id" id="management-product-supplier"><option value="">Sin proveedor</option></select></label><label>Costo<input name="average_cost" type="number" min="0" step="0.01" value="0" required></label><label>Precio de venta<input name="current_price" type="number" min="0.01" step="0.01" required></label><label>Margen mínimo %<input name="minimum_margin_percent" type="number" min="0" max="100" step="0.01" value="20" required></label><label class="check-field"><input name="perishable" type="checkbox"> Producto perecedero</label><button class="btn btn-primary" type="submit">Crear producto</button></form><p id="management-product-message" class="form-message"></p><div class="product-management-list" id="management-products-list"></div>';
  catalogGrid?.prepend(productPanel);
  document.querySelectorAll('[data-management-tab]').forEach(button=>button.addEventListener('click',()=>{
    document.querySelectorAll('[data-management-tab]').forEach(x=>x.classList.toggle('active',x===button));
    document.querySelectorAll('[data-management-panel]').forEach(x=>x.classList.toggle('active',x.dataset.managementPanel===button.dataset.managementTab));
  }));
  async function loadCatalog(kind){const target=document.querySelector(`[data-list="${kind}"]`);if(!target)return;const r=await fetch(`/api/v1/${kind}`),o=await r.json(),rows=o.data||[];target.innerHTML=rows.length?rows.map(x=>`<div class="management-row"><span><strong>${escape(x.name)}</strong><small>${escape(x.code)}</small></span><span class="status-pill">${x.active===false?'Inactivo':'Activo'}</span></div>`).join(''):'<div class="empty-state compact"><p>Sin registros.</p></div>'}
  async function loadProducts(){const [pr,cr,sr]=await Promise.all([fetch('/api/v1/products'),fetch('/api/v1/categories'),fetch('/api/v1/suppliers')]),products=(await pr.json()).data||[],categories=(await cr.json()).data||[],suppliers=(await sr.json()).data||[];document.getElementById('management-product-category').innerHTML='<option value="">Sin categoría</option>'+categories.map(x=>`<option value="${x.id}">${escape(x.name)}</option>`).join('');document.getElementById('management-product-supplier').innerHTML='<option value="">Sin proveedor</option>'+suppliers.map(x=>`<option value="${x.id}">${escape(x.name)}</option>`).join('');document.getElementById('management-products-list').innerHTML=products.length?products.map(x=>`<article class="product-management-row"><div><strong>${escape(x.name)}</strong><small>${escape(x.sku)}${x.barcode?' · '+escape(x.barcode):''}</small></div><span><small>Costo</small><strong>$${Number(x.average_cost||0).toFixed(2)}</strong></span><span><small>Precio</small><strong>$${Number(x.current_price||0).toFixed(2)}</strong></span><span class="status-pill">${x.perishable?'Perecedero':'Regular'}</span></article>`).join(''):'<div class="empty-state compact"><p>No hay productos. Crea el primero con el formulario superior.</p></div>'}
  document.getElementById('management-product-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,d=new FormData(form),payload={sku:d.get('sku'),name:d.get('name'),barcode:d.get('barcode')||null,unit:d.get('unit'),category_id:d.get('category_id')||null,supplier_id:d.get('supplier_id')||null,average_cost:d.get('average_cost'),current_price:d.get('current_price'),minimum_margin_percent:d.get('minimum_margin_percent'),perishable:d.has('perishable')},r=await fetch('/api/v1/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),o=await r.json(),message=document.getElementById('management-product-message');message.className=`form-message ${r.ok?'success':'error'}`;message.textContent=r.ok?'Producto creado. Ahora registra existencias desde Inventario y compras.':(o.error?.message||'No se pudo crear el producto');if(r.ok){form.reset();form.unit.value='unidad';form.average_cost.value='0';form.minimum_margin_percent.value='20';await loadProducts()}};
  document.querySelectorAll('.management-form[data-kind]').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const kind=form.dataset.kind,data=Object.fromEntries(new FormData(form).entries()),message=form.nextElementSibling,r=await fetch(`/api/v1/${kind}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),o=await r.json();message.className=`form-message ${r.ok?'success':'error'}`;message.textContent=r.ok?'Registro creado correctamente.':(o.error?.message||'No se pudo guardar');if(r.ok){form.reset();await loadCatalog(kind)}}));
  async function loadUsers(){const [ur,rr]=await Promise.all([fetch('/api/v1/security/users'),fetch('/api/v1/security/roles')]),users=await ur.json(),roles=await rr.json(),select=document.getElementById('management-role');select.innerHTML=(roles.data||[]).map(x=>`<option value="${escape(x.code)}">${escape(x.name)}</option>`).join('');document.getElementById('management-users-body').innerHTML=(users.data||[]).map(x=>`<tr><td>${escape(x.name)}</td><td>${escape(x.email)}</td><td>${escape((x.roles||[]).join(', '))}</td><td><span class="status-pill">${escape(x.status)}</span></td></tr>`).join('')||'<tr><td colspan="4">Sin usuarios.</td></tr>'}
  const permissionLabels={"products.read":"Ver productos","products.write":"Gestionar productos","sales.read":"Ver ventas","sales.write":"Crear ventas","sales.confirm":"Confirmar ventas","payments.read":"Ver pagos","payments.write":"Procesar pagos","payments.refund":"Reembolsar pagos","inventory.read":"Ver inventario","inventory.receive":"Recibir inventario","inventory.count":"Realizar conteos","inventory.adjust":"Ajustar inventario","purchases.read":"Ver compras","purchases.write":"Crear compras","purchases.receive":"Recibir compras","customers.read":"Ver clientes","customers.write":"Gestionar clientes","customers.analyze":"Analizar clientes","customers.promote":"Promocionar clientes","returns.write":"Registrar devoluciones","reports.read":"Consultar informes","catalogs.read":"Ver catálogos","catalogs.write":"Gestionar catálogos","settings.read":"Ver configuración","settings.write":"Editar configuración","security.audit.read":"Ver auditoría","security.users.read":"Ver usuarios y roles","security.users.write":"Gestionar usuarios y roles"};
  document.getElementById('management-permissions').innerHTML=Object.entries(permissionLabels).map(([value,label])=>`<label><input type="checkbox" name="permissions" value="${value}"> ${label}</label>`).join('');
  async function loadRoles(){const r=await fetch('/api/v1/security/roles'),o=await r.json(),rows=o.data||[];document.getElementById('management-roles-list').innerHTML=rows.map(role=>`<article class="role-card"><div><strong>${escape(role.name)}</strong><small>${escape(role.code)} · ${role.system?'Rol del sistema':'Rol personalizado'}</small></div><span>${role.permissions.includes('*')?'Acceso total':role.permissions.length+' permisos'}</span><details><summary>Ver permisos</summary><p>${role.permissions.map(escape).join(' · ')}</p></details></article>`).join('')||'<div class="empty-state compact"><p>Sin roles configurados.</p></div>'}
  document.getElementById('management-role-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,d=new FormData(form),payload={code:d.get('code'),name:d.get('name'),permissions:d.getAll('permissions')},message=document.getElementById('management-role-message');if(!payload.permissions.length){message.className='form-message error';message.textContent='Selecciona al menos un permiso.';return}const r=await fetch('/api/v1/security/roles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),o=await r.json();message.className=`form-message ${r.ok?'success':'error'}`;message.textContent=r.ok?'Rol creado correctamente.':(o.error?.message||'No se pudo crear el rol');if(r.ok){form.reset();await Promise.all([loadRoles(),loadUsers()])}};
  document.getElementById('management-user-form')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,data=Object.fromEntries(new FormData(form).entries());data.roles=[data.roles];const r=await fetch('/api/v1/security/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),o=await r.json(),message=document.getElementById('management-user-message');message.className=`form-message ${r.ok?'success':'error'}`;message.textContent=r.ok?'Usuario creado correctamente.':(o.error?.message||'No se pudo crear');if(r.ok){form.reset();await loadUsers()}});
  async function loadSettings(){const r=await fetch('/api/v1/security/settings'),o=await r.json(),form=document.getElementById('business-settings-form');if(!r.ok||!form)return;Object.entries(o.data).forEach(([key,value])=>{if(form.elements[key])form.elements[key].value=value})}
  document.getElementById('business-settings-form')?.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget).entries());data.low_stock_threshold=Number(data.low_stock_threshold);data.expiry_warning_days=Number(data.expiry_warning_days);const r=await fetch('/api/v1/security/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),o=await r.json(),message=document.getElementById('business-settings-message');message.className=`form-message ${r.ok?'success':'error'}`;message.textContent=r.ok?'Configuración guardada.':(o.error?.message||'No se pudo guardar')});
  document.getElementById('management-users-refresh')?.addEventListener('click',loadUsers);
  document.getElementById('management-roles-refresh')?.addEventListener('click',loadRoles);
  document.getElementById('management-products-refresh')?.addEventListener('click',loadProducts);
  Promise.all(['categories','suppliers','locations'].map(loadCatalog));loadProducts();loadUsers();loadRoles();loadSettings();
})();
