(()=>{
  const escape=window.ciEscape||String;
  const tabs=document.querySelector('.management-tabs'),configurationTab=document.querySelector('[data-management-tab="configuracion"]');
  const rolesTab=document.createElement('button');rolesTab.className='btn';rolesTab.dataset.managementTab='roles';rolesTab.textContent='Roles y permisos';tabs?.insertBefore(rolesTab,configurationTab);
  const rolesPanel=document.createElement('div');rolesPanel.className='management-panel';rolesPanel.dataset.managementPanel='roles';rolesPanel.innerHTML='<div class="management-grid"><section class="panel"><div class="panel-head"><div><span class="eyebrow">Control de acceso</span><h2>Nuevo rol</h2></div></div><form id="management-role-form" class="management-form stacked"><label>Código<input name="code" required pattern="[a-z][a-z0-9_-]{2,39}" placeholder="encargado_bodega"></label><label>Nombre<input name="name" required minlength="3" placeholder="Encargado de bodega"></label><fieldset class="permission-grid" id="management-permissions"><legend>Permisos</legend></fieldset><button class="btn btn-primary">Crear rol</button></form><p id="management-role-message" class="form-message"></p></section><section class="panel"><div class="panel-head"><div><span class="eyebrow">RBAC</span><h2>Roles disponibles</h2></div><button class="btn" id="management-roles-refresh">Actualizar</button></div><div id="management-roles-list" class="management-list"></div></section></div>';
  document.querySelector('[data-management-panel="configuracion"]')?.before(rolesPanel);
  document.querySelectorAll('[data-management-tab]').forEach(button=>button.addEventListener('click',()=>{
    document.querySelectorAll('[data-management-tab]').forEach(x=>x.classList.toggle('active',x===button));
    document.querySelectorAll('[data-management-panel]').forEach(x=>x.classList.toggle('active',x.dataset.managementPanel===button.dataset.managementTab));
  }));
  async function loadCatalog(kind){const target=document.querySelector(`[data-list="${kind}"]`);if(!target)return;const r=await fetch(`/api/v1/${kind}`),o=await r.json(),rows=o.data||[];target.innerHTML=rows.length?rows.map(x=>`<div class="management-row"><span><strong>${escape(x.name)}</strong><small>${escape(x.code)}</small></span><span class="status-pill">${x.active===false?'Inactivo':'Activo'}</span></div>`).join(''):'<div class="empty-state compact"><p>Sin registros.</p></div>'}
  document.querySelectorAll('.management-form[data-kind]').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const kind=form.dataset.kind,data=Object.fromEntries(new FormData(form).entries()),message=form.nextElementSibling,r=await fetch(`/api/v1/${kind}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),o=await r.json();message.className=`form-message ${r.ok?'success':'error'}`;message.textContent=r.ok?'Registro creado correctamente.':(o.error?.message||'No se pudo guardar');if(r.ok){form.reset();await loadCatalog(kind)}}));
  async function loadUsers(){const [ur,rr]=await Promise.all([fetch('/api/v1/security/users'),fetch('/api/v1/security/roles')]),users=await ur.json(),roles=await rr.json(),select=document.getElementById('management-role');select.innerHTML=(roles.data||[]).map(x=>`<option value="${escape(x.code)}">${escape(x.name)}</option>`).join('');document.getElementById('management-users-body').innerHTML=(users.data||[]).map(x=>`<tr><td>${escape(x.name)}</td><td>${escape(x.email)}</td><td>${escape((x.roles||[]).join(', '))}</td><td><span class="status-pill">${escape(x.status)}</span></td></tr>`).join('')||'<tr><td colspan="4">Sin usuarios.</td></tr>'}
  const permissionLabels={"products.read":"Ver productos","products.write":"Gestionar productos","sales.read":"Ver ventas","sales.write":"Crear ventas","sales.confirm":"Confirmar ventas","payments.read":"Ver pagos","payments.write":"Procesar pagos","payments.refund":"Reembolsar pagos","inventory.read":"Ver inventario","inventory.receive":"Recibir inventario","inventory.count":"Realizar conteos","inventory.adjust":"Ajustar inventario","purchases.read":"Ver compras","purchases.write":"Crear compras","purchases.receive":"Recibir compras","customers.read":"Ver clientes","customers.write":"Gestionar clientes","customers.analyze":"Analizar clientes","customers.promote":"Promocionar clientes","returns.write":"Registrar devoluciones","reports.read":"Consultar informes","catalogs.read":"Ver catálogos","catalogs.write":"Gestionar catálogos","settings.read":"Ver configuración","settings.write":"Editar configuración","security.audit.read":"Ver auditoría","security.users.read":"Ver usuarios y roles","security.users.write":"Gestionar usuarios y roles"};
  document.getElementById('management-permissions').innerHTML=Object.entries(permissionLabels).map(([value,label])=>`<label><input type="checkbox" name="permissions" value="${value}"> ${label}</label>`).join('');
  async function loadRoles(){const r=await fetch('/api/v1/security/roles'),o=await r.json(),rows=o.data||[];document.getElementById('management-roles-list').innerHTML=rows.map(role=>`<article class="role-card"><div><strong>${escape(role.name)}</strong><small>${escape(role.code)} · ${role.system?'Rol del sistema':'Rol personalizado'}</small></div><span>${role.permissions.includes('*')?'Acceso total':role.permissions.length+' permisos'}</span><details><summary>Ver permisos</summary><p>${role.permissions.map(escape).join(' · ')}</p></details></article>`).join('')||'<div class="empty-state compact"><p>Sin roles configurados.</p></div>'}
  document.getElementById('management-role-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,d=new FormData(form),payload={code:d.get('code'),name:d.get('name'),permissions:d.getAll('permissions')},message=document.getElementById('management-role-message');if(!payload.permissions.length){message.className='form-message error';message.textContent='Selecciona al menos un permiso.';return}const r=await fetch('/api/v1/security/roles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),o=await r.json();message.className=`form-message ${r.ok?'success':'error'}`;message.textContent=r.ok?'Rol creado correctamente.':(o.error?.message||'No se pudo crear el rol');if(r.ok){form.reset();await Promise.all([loadRoles(),loadUsers()])}};
  document.getElementById('management-user-form')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,data=Object.fromEntries(new FormData(form).entries());data.roles=[data.roles];const r=await fetch('/api/v1/security/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),o=await r.json(),message=document.getElementById('management-user-message');message.className=`form-message ${r.ok?'success':'error'}`;message.textContent=r.ok?'Usuario creado correctamente.':(o.error?.message||'No se pudo crear');if(r.ok){form.reset();await loadUsers()}});
  async function loadSettings(){const r=await fetch('/api/v1/security/settings'),o=await r.json(),form=document.getElementById('business-settings-form');if(!r.ok||!form)return;Object.entries(o.data).forEach(([key,value])=>{if(form.elements[key])form.elements[key].value=value})}
  document.getElementById('business-settings-form')?.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget).entries());data.low_stock_threshold=Number(data.low_stock_threshold);data.expiry_warning_days=Number(data.expiry_warning_days);const r=await fetch('/api/v1/security/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),o=await r.json(),message=document.getElementById('business-settings-message');message.className=`form-message ${r.ok?'success':'error'}`;message.textContent=r.ok?'Configuración guardada.':(o.error?.message||'No se pudo guardar')});
  document.getElementById('management-users-refresh')?.addEventListener('click',loadUsers);
  document.getElementById('management-roles-refresh')?.addEventListener('click',loadRoles);
  Promise.all(['categories','suppliers','locations'].map(loadCatalog));loadUsers();loadRoles();loadSettings();
})();
