(()=>{
  const payment=document.getElementById('payment-form'),pmsg=document.getElementById('payment-message'),body=document.getElementById('security-audit-body'),escape=window.ciEscape||String;
  const paymentEyebrow=payment?.closest('.panel')?.querySelector('.eyebrow');if(paymentEyebrow)paymentEyebrow.textContent='Cobro de la venta';
  const actions=document.createElement('div');actions.className='post-payment-actions';actions.hidden=true;actions.innerHTML='<strong>Venta y cobro finalizados</strong><span>Elige el siguiente paso de la operación.</span><div><button class="btn" type="button" data-next-page="inventario">Comprobar inventario</button><button class="btn btn-primary" type="button" data-next-page="informes">Preparar informe</button></div>';pmsg?.after(actions);
  actions.querySelectorAll('[data-next-page]').forEach(button=>button.addEventListener('click',()=>{const page=button.dataset.nextPage,target=document.querySelector(`.nav-item[data-page="${page}"]`);window.ciShowPage(page,target.querySelector('.nav-label').textContent)}));
  const tokenField=payment?.elements.payment_method_token?.closest('label'),last4Field=payment?.elements.last4?.closest('label');
  function syncPaymentFields(){if(!payment)return;const method=payment.elements.method.value,isCash=method==='cash',isCard=method==='card';tokenField.classList.add('conditional-field');last4Field.classList.add('conditional-field');tokenField.hidden=isCash;last4Field.hidden=!isCard;payment.elements.payment_method_token.required=!isCash;payment.elements.last4.required=isCard;if(isCash){payment.elements.payment_method_token.value='';payment.elements.last4.value=''}else if(!isCard){payment.elements.last4.value=''}}
  payment?.elements.method?.addEventListener('change',syncPaymentFields);syncPaymentFields();
  function prefillPending(){const pending=JSON.parse(sessionStorage.getItem('ci-pending-sale')||'null');if(payment&&pending){payment.sale_id.value=pending.id;payment.amount.value=pending.total;pmsg.className='form-message info';pmsg.textContent=`La venta ${pending.number} está pendiente de cobro. Verifica el importe y el medio de pago.`;actions.hidden=true}}
  window.addEventListener('ci:pending-sale',prefillPending);prefillPending();
  if(payment)payment.onsubmit=async e=>{e.preventDefault();const d=new FormData(payment),method=d.get('method'),methodLabels={cash:'efectivo',card:'tarjeta tokenizada',wallet:'billetera electrónica',transfer:'transferencia'},payload={sale_id:d.get('sale_id'),method,amount:d.get('amount'),payment_method_token:method==='cash'?null:d.get('payment_method_token'),brand:method==='card'?'Tokenizada':null,last4:method==='card'?d.get('last4'):null},r=await fetch('/api/v1/payments',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(payload)}),o=await r.json();pmsg.className=`form-message ${r.ok?'success':'error'}`;pmsg.textContent=r.ok?`Cobro aprobado por ${methodLabels[method]}. La venta quedó pagada.`:window.ciFriendlyError(o,'No se pudo procesar el cobro. Revisa los datos e inténtalo nuevamente.');if(r.ok){sessionStorage.removeItem('ci-pending-sale');payment.reset();syncPaymentFields();actions.hidden=false;window.dispatchEvent(new CustomEvent('ci:pagechange',{detail:{page:'caja'}}))}else actions.hidden=true};
  const securityPage=document.getElementById('page-seguridad');[...(securityPage?.querySelectorAll('.metric-card')||[])].find(card=>card.querySelector('span')?.textContent.trim()==='Pasarela')?.remove();
  document.querySelector('#page-caja .sandbox-banner')?.remove();
  const auditPanel=body?.closest('.panel'),auditMessage=document.createElement('p');auditMessage.className='form-message';auditMessage.setAttribute('role','status');auditMessage.setAttribute('aria-live','polite');
  const filters=document.createElement('form');filters.className='audit-filters';filters.innerHTML='<label>Acción<input name="action" placeholder="Ej. inicio de sesión"></label><label>Resultado<select name="outcome"><option value="">Todos</option><option value="success">Correcto</option><option value="failure">Fallido</option><option value="blocked">Bloqueado</option></select></label><label>Responsable<input name="actor" placeholder="Identificador de usuario"></label><label>Desde<input name="date_from" type="date"></label><label>Hasta<input name="date_to" type="date"></label><button class="btn" type="submit">Aplicar filtros</button><button class="btn" type="button" data-clear-audit>Limpiar</button><button class="btn btn-primary" type="button" data-audit-pdf>Descargar PDF</button>';
  auditPanel?.querySelector('.panel-head')?.after(filters);filters.after(auditMessage);
  const params=()=>new URLSearchParams([...new FormData(filters)].filter(([,value])=>value)),actionLabels={'auth.login':'Inicio de sesión','security.bootstrap':'Administrador inicial creado','report.generate':'Informe generado','settings.update':'Configuración actualizada','payment.process':'Pago procesado'},entityLabels={user:'Usuario',report:'Informe',payment:'Pago',business:'Negocio'},outcomeLabels={success:'Correcto',approved:'Aprobado',failure:'Fallido',blocked:'Bloqueado'},actorLabel=value=>/^[a-f\d]{24}$/i.test(String(value||''))?`Usuario …${String(value).slice(-6)}`:'Sistema';
  body?.closest('table')?.querySelectorAll('th')?.forEach(th=>{if(th.textContent.trim()==='Actor')th.textContent='Responsable'});
  async function audit(showFeedback=false){if(!body)return;body.innerHTML='<tr><td colspan="5">Consultando eventos…</td></tr>';try{const r=await fetch(`/api/v1/security/audit?${params()}`),o=await r.json();if(!r.ok)throw new Error(window.ciFriendlyError(o,'No se pudo consultar la auditoría.'));const rows=o.data||[];body.innerHTML=rows.length?rows.map(x=>`<tr><td>${new Date(x.occurred_at).toLocaleString('es-EC')}</td><td title="${escape(x.action)}">${escape(actionLabels[x.action]||'Acción registrada')}</td><td>${escape(entityLabels[x.entity_type]||'Sistema')}</td><td title="Identificador protegido">${escape(actorLabel(x.actor_id))}</td><td><span class="status-pill">${escape(outcomeLabels[x.outcome]||'Registrado')}</span></td></tr>`).join(''):'<tr><td colspan="5">No existen eventos con estos filtros.</td></tr>';if(showFeedback){auditMessage.className='form-message success';auditMessage.textContent=`Consulta completada: ${rows.length} evento${rows.length===1?'':'s'} encontrado${rows.length===1?'':'s'}.`}}catch(error){body.innerHTML='<tr><td colspan="5">No fue posible cargar los eventos.</td></tr>';auditMessage.className='form-message error';auditMessage.textContent=error.message}}
  filters.onsubmit=e=>{e.preventDefault();audit(true)};filters.querySelector('[data-clear-audit]').onclick=()=>{filters.reset();audit(true)};filters.querySelector('[data-audit-pdf]').onclick=async()=>{try{const r=await fetch(`/api/v1/security/audit/pdf?${params()}`);if(!r.ok)throw new Error('No se pudo generar el PDF de auditoría.');const blob=await r.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='auditoria-seguridad.pdf';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);auditMessage.className='form-message success';auditMessage.textContent='PDF de auditoría generado con los filtros actuales.'}catch(error){auditMessage.className='form-message error';auditMessage.textContent=error.message}};
  document.getElementById('security-refresh')?.addEventListener('click',()=>audit(false));window.addEventListener('ci:pagechange',event=>{if(event.detail?.page==='seguridad')audit(false)});audit(false);
})();
