(()=>{
  const payment=document.getElementById('payment-form'),pmsg=document.getElementById('payment-message'),body=document.getElementById('security-audit-body'),escape=window.ciEscape||String;
  const actions=document.createElement('div');actions.className='post-payment-actions';actions.hidden=true;actions.innerHTML='<strong>Venta finalizada</strong><span>Comprueba el inventario o genera el informe PDF.</span><div><button class="btn" type="button" data-next-page="inventario">Ver inventario</button><button class="btn btn-primary" type="button" data-next-page="informes">Generar informe PDF</button></div>';pmsg?.after(actions);
  actions.querySelectorAll('[data-next-page]').forEach(button=>button.addEventListener('click',()=>{const page=button.dataset.nextPage,target=document.querySelector(`.nav-item[data-page="${page}"]`);window.ciShowPage(page,target.querySelector('.nav-label').textContent)}));
  function prefillPending(){const pending=JSON.parse(sessionStorage.getItem('ci-pending-sale')||'null');if(payment&&pending){payment.sale_id.value=pending.id;payment.amount.value=pending.total;pmsg.className='form-message info';pmsg.textContent=`Cobro pendiente de ${pending.number}. Verifica el medio y procesa el pago.`;actions.hidden=true}}
  window.addEventListener('ci:pending-sale',prefillPending);prefillPending();
  if(payment)payment.onsubmit=async e=>{e.preventDefault();const d=new FormData(payment),method=d.get('method'),payload={sale_id:d.get('sale_id'),method,amount:d.get('amount'),payment_method_token:method==='cash'?null:(d.get('payment_method_token')||'tok_approved_demo'),brand:method==='card'?'Tokenizada':null,last4:d.get('last4')||null},r=await fetch('/api/v1/payments',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(payload)}),o=await r.json();pmsg.className=`form-message ${r.ok?'success':'error'}`;pmsg.textContent=r.ok?`Cobro completado: pago ${o.data.status} mediante ${o.data.provider}.`:(o.error?.message||'No se pudo procesar');if(r.ok){sessionStorage.removeItem('ci-pending-sale');payment.reset();actions.hidden=false}};

  const securityPage=document.getElementById('page-seguridad');
  [...(securityPage?.querySelectorAll('.metric-card')||[])].find(card=>card.querySelector('span')?.textContent.trim()==='Pasarela')?.remove();
  const auditPanel=body?.closest('.panel');
  const filters=document.createElement('form');filters.className='audit-filters';filters.innerHTML='<label>Acción<input name="action" placeholder="Ej. auth.login"></label><label>Resultado<select name="outcome"><option value="">Todos</option><option value="success">Correcto</option><option value="failure">Fallido</option><option value="blocked">Bloqueado</option></select></label><label>Actor<input name="actor" placeholder="Id. del usuario"></label><label>Desde<input name="date_from" type="date"></label><label>Hasta<input name="date_to" type="date"></label><button class="btn" type="submit">Aplicar filtros</button><button class="btn" type="button" data-clear-audit>Limpiar</button><button class="btn btn-primary" type="button" data-audit-pdf>Descargar PDF</button>';
  auditPanel?.querySelector('.panel-head')?.after(filters);
  const params=()=>new URLSearchParams([...new FormData(filters)].filter(([,value])=>value));
  async function audit(){if(!body)return;body.innerHTML='<tr><td colspan="5">Consultando eventos…</td></tr>';const r=await fetch(`/api/v1/security/audit?${params()}`),o=await r.json(),rows=o.data||[];body.innerHTML=rows.length?rows.map(x=>`<tr><td>${new Date(x.occurred_at).toLocaleString('es-EC')}</td><td>${escape(x.action)}</td><td>${escape(x.entity_type)}</td><td>${escape(x.actor_id)}</td><td><span class="status-pill">${escape(x.outcome)}</span></td></tr>`).join(''):'<tr><td colspan="5">No existen eventos con estos filtros.</td></tr>'}
  filters.onsubmit=e=>{e.preventDefault();audit()};filters.querySelector('[data-clear-audit]').onclick=()=>{filters.reset();audit()};filters.querySelector('[data-audit-pdf]').onclick=async()=>{const r=await fetch(`/api/v1/security/audit/pdf?${params()}`),blob=await r.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='auditoria-seguridad.pdf';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
  document.getElementById('security-refresh')?.addEventListener('click',audit);
  window.addEventListener('ci:pagechange',event=>{if(event.detail?.page==='seguridad')audit()});
  audit();
})();
